### hatebin code: https://hatebin.com/fbtyukfdto
### Browse through all the 10 pages on the web-site 
## https://find-and-update.company-information.service.gov.uk/register-of-disqualifications/A?page=1
## collect/print all the hyperlinks that lead to each individual profile in terminal/CSV
## Concatenate the collected urls and go through each profile (you can create another program, by just looping through the list) 
## Collect the below information (if existent on each profile) and print it in CSV file
## name, DOB, nationality, address,start and end date, case referrence

## Desired output:
## profileUrl + ‘!’ + name + ‘!’ + dob + ‘!’ + nationality + ‘!’ + address + ‘!’  + startDate + ‘!’ + endDate  + ‘!’ + caseReference + ‘\n’


from selenium import webdriver
from selenium.webdriver.common.by import By
import time
import csv
from selenium.common.exceptions import NoSuchElementException
 
driver = webdriver.Chrome()
#Creating/Opening a file to write the data in. Please change the path to the correct file on your computer.
with open(r'C:\Users\Karolina.Gugudis\Desktop\Directors names, DOB.csv', 'w', encoding="utf-8") as f: # w is for writing a new file
    f.write('url name DOB nationality address startDate endDate caseRef  \n')
    
driver.get('https://find-and-update.company-information.service.gov.uk/register-of-disqualifications/A')
 
driver.maximize_window()
 
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
time.sleep(2)
allprofiles=[
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Tu7TMRRdse-JK5buqQUQqU8JGnk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/oeraPC5Kp0aLR_fuF9wN-taP8oM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/OFvGoUBHx973GqGALm-p9vIuM_s',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/X-_BQLfCagqHlpMPduoRl7YtkSY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/5sGuL75B1uEVrQhfhJp3IPzTDAg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/7b1v6gIsHqua7GkKkMMjpmir-uE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/9M18cThNVUwNd_FuGHdIJIAK74U',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/7gV4daxlf4yZ9MJSVSDL8NuULeA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/NP3GGY3JbvXOKH127qli2VyEjWg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ROsIUUyAIhpkkkUH3aFRpHp48_U',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Y1k7Vnxfq0aiNmyUWNQUO21bcyA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/am2XwS0mM_p1V478XfjDb7XbS7I',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Z-5DVrNVD3_DADsY4ICvyocwWOI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Le2SFuFbLheHzsA6AkfiOvsVT4o',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ItHtBu7Glcr2sBQ47sYImFLIVMY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/rjWt2e1zTDiQwx2OeoHCBx1LTOw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Mj4UrCPmH22jj1dGzbBL26hX1Io',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zyjtb-iIY-K00WwbBVNav4BTV7o',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/msB5fXi1mQEzH1UQx-t-dHENKM0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/WhsrIi2hK5x0UUw6qxbC2fyEZ3U',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/d388J373lhecDEspg7X-jC74PUk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/2mR1f8PjqRMLYDEIU0a7KKRSkGI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ra6fgbv1QVPXJa3hFlfAtLsJlC4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/IXYJtfcov70-Orun4VVOqDSjTjg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/FmkLLZ75-liQP_OdXqNn2wIvMTs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/FY7Daf-xSpqZ3Tl3WEskPT8-IlY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/tQs7Q6m8UsfLWB8PKHMuKpv2Sfo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/hdXAVuctbU9MIbBiph_JAeWQ8yI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/MNuLBVKZxLhku5XmtnK7S2nxfgI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/IuS-STWLf_I49DZSsMFykGbDmEM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/8q4y3Q7PR4nV4iLVaLA-xDAEoWQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/J--TtVykZKcJCUGkhy0Eezztifk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/EyAer-Gz8YNqUwrmS-_i9mKKzOs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Ck4ITDUaAGp5oEeQqBeyIg8o2Ts',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zqyCHMvy_0gO-gq_FuffN39cHwQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/smeSeW8xXfXeq0PdcdOn57FpIrc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/We-HLdmhTlHgfmc2_h4DXhk1mc0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/V5cAEocKh1Ml42niIP77w4hhF_M',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/vvUhsPAwrUyol4DSwsXSfrzF6ZY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/coz8WClQjfXMEZwSQWyPax-wpEA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/9lh_qOPNRJbohPfotrSvRFKfHw4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/RWgx5BpFKh8T8oXXc2hB80AVXZ0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/4K6pyhNGVnNospioAjfP4v56CwQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/B0PaeMrGGaZuN4Z3HfH4vMcpMpQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/YfH7pfydBolV_FqTSh2wG2mHxOI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ebTL4VRCCqDDPmnZeAm0TIBZA6s',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/6Mo9i-PUHKtpK8-RNOSU0hHWccU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/t8S-Om7FieNyt7CnywO64loR3Gs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/fQPASth405TbUbYuRjx--ITlwPs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/CCvwgWkkDmxv_2alrrJDVd93NKQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/AumkZKmgejNRa_ljs4NkK9lcHmQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/MODgaU_kdM2mFjGIZL6C2I49YVY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/A-L7aN0yZgtBvkDIP0kL5V7f0bQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/7OQgzMqq3Nfez6IiRGvPvHasxgI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/6o6kQ2Kii7Fykctf_mLDnwkWO7s',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/KSOfDen3RhWLNbKg9Xl231Jd_0Q',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/-CGEX0VORVeFVsORGj7kieHksH8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/0Vf7xPP5UZt6fLXxoQxU88vsczk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/jrnOHgGUdHR5gdBoM1PxJJi1xxA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/sQbX91svPFWohBjtBrkoDwe_aF4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/yYK-mlHXy2GVUBFDZMzbjEVH420',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/dic1D2bASHIXqSojimnrL4fxs_c',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/YQw56VaCsW5hb0nkLmkoVEuJLkA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/MfWjBRYTDI072zcACB4BefhBgJY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/z2bkWnKtbFuyVIMlp0cW_PvIi2s',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/QiqaPMAPX4cQjPHc4AEkRRyUolk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/aOBCAgCtYjFzlMUEAec_Y3YRTUs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/mtCL8E3XEPug2eaChp8mNLMdB_4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/rlfrWxTtui2tU_prONkcUnrGi0g',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/FZD2vDOF8Hl0gh0STdqSBjpxg7w',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/1ta7DYuO-CzJ8NSIfQB1-_x2pSI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Q00W8wdZ84TujiZOZUGxiDDwpYs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/6GbV5vxyAyXkI9uqew68qP3QlAg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/arCEce4yOIH1Gy749Z3Q7c-GjXQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/MDQTIpsuWetQsq0_d1SfMU9n0Ds',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/pby0t4kkKWYjuhOq8G2kaPhzaSo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/TFrx_6erYwxmlhlC4uZosbhdIyk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/MBcTO7a0BiUO3WhnMcXyAOpiQuA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/eUbZpFAFDQeYqVLx_Mx4KlM4FN0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/lI0krQVSySWenzw8YdAGfnsSUmI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/o7rONI7kMF2s4Hg6IiBpc2Y5bG0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/n7B3lA8NjjCCGdXiO2bNa0jd9eE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/3nPfAP8-y7QF4meo5L4hAnLLR94',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/CY7tbdL1thltlikmhlnTRFt-NLE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ml4cv8YCr4tzuC2efo60GAzzWmE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Q4pNzc1FAMUn5Vn3pjGiaDzUCQE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/FffPKYxQC-_juGVHmX0AOATgrqc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/SzTSqAe_LuNRljwgo3-_BVrmbLw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/O33raSqYnXdcu4jBxUXeWHExRlk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/kNn2exnF399BxsWkvnupbz2F5C0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/00ev7-oa8RE1X8GoUna2WkGtcz8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/R-L7geV-0wnI7TT8PhWs6UyBNsw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/g_jQa8KB4aZtv-Mvh0z3-C4Hk24',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/2HcacY_Iwc1mpbjFF9PXUK0chyw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Fn5_3bmMSVcWRUk1rVhqmXYkI-M',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/hpuY685GEHmVPCXxofTAx1o70Y8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/4WKi4_Y62tLCmZtEfmJTo7LqYeE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/T3cvXq3KD4z4LAdfeboC0RI8BBA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/DXtfwq3LQJKlu3Gx4B-K0msoIfw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ZGB4njLSWEOUGVvWX8Sfp2miZlU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/hJIkLm5U2D8w635zI4nQRlzibF8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/N83tyobfnusRYfgcgjqvHLP-ysM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/R9S6a4-iFLZ6aOx2evwz-7r2DiA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/jVE6uAtc312PmRa7NJGC4_cwDdQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/6np4b7nrEvTtTU1vqw4402ZNq5I',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Ja3LmQT1mnu6PTEOVKkmlLAM7EE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/DtnNNKmOine6Mh7WW4neN8Xt5gM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/OX0iBDu96JzCimL-ZJ4jCbtMX6U',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ByqaJSw_uxfB7UgZUhI6USBaQgQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/yHw3nXYL-UDAMLV0A5-2N8qNviM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/MuSLYrJo19w6qwH2vSInDdUfAHI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/4gAv52ewvXoGCz3uusiduKlWvSg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/dC5Ab9u5JmHtlNJatElb4FJqALI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/EVxUlzZUQUsANRn5zFvVr14BvcM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/-7FYu45lwlZWMtxsNHJ_0ZCD0kU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ZyK8VxJfpKUD38Ow5qYNGeZZy0Q',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/_IaO36ShFJr-glhhIN8ZOZAk-Yk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/wSrsymE86ArX9Y3glxHLip0JQTg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/308q1nVIflDV_HJ5TSC2JZPHKIw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/vSfmd5w6EZwei7c9c0oVBAjzgeU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/oo5YDAkw8lxBRb283JEl3daSBck',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/-WeaYGI6_hfAu0XoyJahDP45_PE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/RBglguO9SejWz57ZwtYB3OUGvdw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/s6AhYVeEUqeifIiTYOEV4gmraNc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/knhNeYUEurS_ihiZBdjTdDuKI0Q',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/TXDLtPOkUkm8vl6yEKfoV69g8yU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/wLVxFEMarpeOg_wWfPSL9X_YXLQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/dr75c_erCrdVq1OM5mgS5xoxEc0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/dr6jcKxQDLrvA7Xr88D_2vcmclk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/23xftsPdGWGo70Z-A13BF7D-xX0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/jSf8bMDj-9jWKqKfx1uotpoySZQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Dpi0LWB4jnTVJSVNUTDuCthDgGw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/r7Zva6KngdOIabwo4lln0djNFOs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/1WNflUJWSzyNzfBFL2OfhzA6RlM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zh1-TabQ2dUgCufPtUlf3KvFeP0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ZhXYhcBhdDEdM4o5hsBAQVTa4AM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/FI9kaMqPKgcsgnFW36XqaPE6kL8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/QJYq-dxq98fGqB_c_WJHzdGohoM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/YxoUXYSTAapY8G0CqpaM5SNrdjU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/HBbPjY9ZMpqgodLEh8qiMPYR_bs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/R9Vp7vfU0lq6W98C4AvwQJEbf9M',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/1Lrt-2lbrUvFcub3mijnP8QJpRM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/i_udfwyCzrcBaop5ODmgdLlIy4E',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/sKXxfIy65k_9WqWmevuCsYSy_pI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/pVGz5U_HnrtdpEnk_ktMzOTw42c',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/sIphuTIl1gpIcPrDVXUy7FusXG4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/vnCm1gHckMjPbBHhbarw4k2mOIo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/QFf-6FXhnnd-26On0o1dz3wcI6Y',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/wi37du55MZ2mBwwqmu2UJXi0Ul4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Ig3UcscmS1P8j2Is-L96ntZkWkc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/c54ctBNIB5bTPlzn-A4bAMTJAiA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/LGjgD9aHeicoiNCLd_N5qKz18Cs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/QZwHjIXxbD_zUUIMB-e742Ndwec',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/6PfizFEiAftlHZzGTsjvpJMvL-I',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/3RU1Dh2gUML2e1YhVsCJgBm8ctg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/7J_KkQPx5dYzzdMUZ4pUs8bMBT4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Y-bu0qZhvKkByM1EK8Qj86RDaXc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/BMQEmORvGupSSxA5tGu6VrzSG7U',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/1s54D7VIG_S0mqU_iNePXmwA1sU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/DA9-yJ7muMg5DhPHspHqf4a0Hfo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/lUGvMflPjJVFPD2-JIqajYtmU3Y',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/E0hBZR6ZDUAinRTkoHmKVGnwlYM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/G-n5WhuJUbnTo935w19s591iZrY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/y6E7k5i9I2UXD1CAUHLb7Ulx5No',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/2rh-ivj58Cpufhi1bUAGbujp0yk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/cVPD-3lZz4L-IYB8UOCPEQpCzvs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Vkiohd9bsUMN_1LNJ-Zei1bOvFg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/mggF_jWKf7hhgUFwpc0DeLWD90A',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/O-bZkjkWR33lCT8w8QMLAyJkqjI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/nbMwllgAHD65fXa0OPr17Q3EEh8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/xoreo7PmGeyUoPCvqXjZ296wtuU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/NCvY78C8ffak-SGfx2PJDE6Vt1U',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Wju1DIYWPUIMtOr-QccZ0kDqdLg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/TxepH4kN34LR8G-FqqrqrrmQYsE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/-lg69muGJmY4JOTJ-4EeV-9lIDA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/5LsxJlsZGWOaffH1Qhn8KTSlNvY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/W08RhAdhID2qFlFhGdVKLGdwCLo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/nOsIg6lBt1FPjafhnczRDvgMuHk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/fhTvbZvdOW0FBYq_drevGcB0Mrg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/RkftF7jy5DtwvraEuEbamxkhE6Y',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/5hj4Ccd1UWm3xwN1Sei6zN9f8C0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/8sD79imTV8VsWIaGXvSYssp1TpY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/LVVaDBSIYN7tQZloIKsku0pmL5c',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zqcnML5xRXXTHS7EeHMD6jS9Zzw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/XGoqS9MHY84u5ESmgpMsGnc3t70',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/5aF5GDHx34pPzbTVfel74ZerWpM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/_Y3iYP2AjU-beAGUew0N6tuGuqo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/jotGL9nQId-ovaxiF7e4YcmOL_A',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Z-p_veN8Bq1JQtAWO9u1iJCeZm8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/MbIwMsDA2v3wT0CxLH1usUfj4ys',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/2xiG844c_WrKFe--4dglo1AKruA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/cNMw5jCdFIX2OJMW2wi2HSugpS4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/KYSR4wp0EXN7jDQ9bb1FzgtAsNg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Jz8InjQfIeLkWjVckCW9pxg1a54',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/2BJHYzuGCsCBqkgHL5ja6qhdO3w',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/FhMckZ-XBuJcPayPy51ZUXNLcJw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/V02t_kb_LZ4zWXIbCvTF0hUtJ7k',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/aVKFgehFVmUmRoTtpW0vmrehr3g',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/XXSx6HvzglT9TuCztwk_UDSotHU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ruIlAQ_LtQSqFRmG47wU80bYtA4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/K75dpyfKtTmNF5l07jHUr4hbtoQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/DZtsmm67wMNx_Oimq5mttGZS31w',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/mVQcSn1EkycGV0xKoWtQd12Jod8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/QnX60T809TRQqYEd9Wq57b78Nu0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/7b1OTqYQkKOGvFkCiR8UAIPiDJE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/YV5y1Wrp9vGtCLAI7wuNS17QYDM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/w-rqMvhz-MKcp5yIcNhkCvRAOzo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/LwwGDQwUldalnUlncTTG3hfdw6g',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/J_sAjBI-hij4w-m8VdhMi9kklAU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/sCYjme_C1yZzGGtU1jAhkDRxaUo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/5y8a5BEvG_tl_ueFoeEihUXiV8Y',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/bOvurordNVu9_9I2GwzOWfZZBDk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/BINldWkeDrurBZX8om29Ku38jbs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/qcRgrA-Sbzn22wHPThFFXTXIg_s',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/VLeH0HUt-Gicvj9IfJLX_d-w9d0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/EiL9svv_y0dIC9PERHxsnuiyhm0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/XHPzWVXGTVsU88ybGnwQ5WZTfHY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/KZxJgJH9TBl35kcd4HR2Jt0TSPw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/qqyPuzu94aQ8aJnEHdbL0R-t1ZM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/V0JcJYKoOGqpdODjOzszN8890hk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/X48zd_Uu1zpy1DpjbxixpBKQRcw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/3mFbig5DxfZOOtdfa5j0PG6MJSY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/eO3-pJqUe1wgaBPkpY_S1PJjg9A',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/_9e3fd4330xlzpfSWPaFtmplsVE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/APEABWaK59P1X3Vw2Rvgdne8r0U',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/k_m79Aj4Xl2lK7eBw35_nzzhqWs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/mO-fZPBVuHrwiE1ZpWMSFlMBMLE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zNsBehvgAPJmZxRxi0WZ_L0hGpQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/cxuY2PuCttd37JTcVoIL6ocUbGk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zqh8h54i7qRkD5UO0-3INVMCCRo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/B3DzHpXTIRD1mRz7gXx5d-qtDCo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/C7Rk3q7qXZNfuc7UoTTn-vHy44o',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/yQ_3Q7nshKCqirexoBoF19PP_hU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/TJLirfrxh7uHIenIpyORPL8vc7k',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/nsvHSoUyGXzJCTGBJY7glVEQbck',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ts76YBCccExVOqiuKZVpTCY6Z3Y',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/lvWncANYIihe6E2MwSMUCig5YDE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/uc7uOeW4ua-Gcpxnp_gyi9W_8jw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Vye7bGe7RzfEw4xQj43E-Uc-WLY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/fNcAkI0weblDJ2TgPdfz9dZulrg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zdNhmiJ9EXcVxxY79VjmC3zunsg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/d5nmZPlgbLTrRbE2xC6BjVCGs4k',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/E6Hd7cBEEAk_uTBDNpUtkONn6h8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/h2S5SNmiRTaBvyUXQHKwLya3rfw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/P_bvPdpjRJFoU0kyb2gPYvzBsOU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/fP8AQeDFen0dwKHVHKPRbmsvHYI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/j6jJ00OE6J0Y9kt-GA9JAA0MZjg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/rQwOHgOtVlpA7_5YA9TLi8Tgqdo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/FPdWx_T5do-IzaXjFFhetBPVmys',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/XIlKiI0TWKwEjzjYM8Qe8msyIzw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/766lWEeMuyhZj1K1dCZvJRVBRT4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/SQyR7YnvtEtDPDZirnlisQzIpFc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/cfj1lAHznmUUfM_AshbSamxnwIY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/MWtvNPcEhwVhFsPddRYimz1prU8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/cgt0-6hSaNauLFQ55speW3XQ-1Y',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/yOtablmnJl95L-T_xYrEpNYE6yo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/B0iwNT657driOOKFR1AAxZJ2OcQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/lzUZUyZOdcqR0QtPGZzCvuADvFg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/RK1NvwOK9921Vb3oz-ZZnR_mM6A',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/RSOSqztOOROdO1NdRo77QGxWBJ4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zFoUq0UhjenvR7ntt61Ra5rnAgg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ijG3y9gbogOx5rGMSHaS6PgwTHs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/6wUbw4oU3esnd3-oJeO5uI707Yo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/anJSJ8wcObMkbMQbjvME2RAMzOc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/1BpzYBWdXba-IsRwBlnTJOs4xi4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ydBWJEWipBC3IbIJ62KywAOyfm4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/NxP5u8bViRmTqVysGksaXXwDEAg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/wG5zI0davg49u8hy8OsGRNp78uA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zhIrmgQQIAFDGJ2PrcTInwGode8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ED0WeAZfdiNHfRwKkLWgCjFXd6g',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/t2AvqAylhiWU3qZHgaW0TACLOyM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/i1ULNI5IxX4_9OrEDAO6I3N4bxs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Q_lGK60hnROLyqJLb7-P-Fln928',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/iCYWWZM0crgQslRmZjCH7yH3WVc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/a06NbzJv7Tn6i7QnnC2gL1BMs4c',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/YipYaXf9Bmk3Iw52a2Dd4ZriX-o',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/4O79zhcpyj2Ul6T099cjh6CSM3c',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/oNqeOlOenhxEhUm27b_oJCEoE-A',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/CgXzgaYJeNTJqhqRP6u__wcs6XQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/W_uUphMcaEuq1E4XKWRcWyM-Amg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/gM7LSRkG-zYp5t1R8THNSs5dXQk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/5ZJB3Up5CQ4DSkgdfdhjHGocR14',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/NDit6Cp8Vsn8EQqcZPAvrCsCejw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/97cB-powB7uvTbswTGe9Va1-15c',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/IdntQRw5wLhenPgJjIZzRmg4kQM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/-uVrVLrPS3CPtEJpC8MlSfHP_-E',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/qF_4qzFDhhOQSx13QKdYXAl4-qo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/jy5BdRCkqGxwg_wgOCVJUBTpZgs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/YycnWdI_dA19ORtZxL9bgBEQJCM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/IF1sEWpUivEKF_mg4Q42qhieBfg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/5yJFKGwyyYvvy92LCm4cy92JHUA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/n18blHjV-fuyyhfKeQWDczhwCQE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/pwyBm2w3RW3biOIwUWM9rkbk8lk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/UAlpMuSl69uBDNoXiaikgvwPTh0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/RMMNwJkAwXzmoIjxPKtDNzHv0FY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/KTFXrV94gGqOUmKEK3gPuBedvmE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/4_XJGomj8f653je5TUUOFjvl16w',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/eDjIap72pevcOjHxAVwy4QYlmdM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/QdHRU2UJjP61j1XefGoxPyJWe80',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/RDLpWrjQHsas8kwbpSzB9Lhj1Xc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/h2MLgHMyHxx2w_v_w-P5IOLk6RM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/6k5HHEQvUo-xKMSL4P90Fvd78Jw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/EE2fM2_3Yk-wNpGPsW4SstunXGg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/y_2b_DaD_5Txexryvp829-iv8Bg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/DzqSUAEoKQNkZFB9rWmI3-pOvMg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/VgEBCzNRvpSmN92W3cvkbTekEnU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/iiA_m-dBGqn8phRmHPIDHSLisKg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/1IiLNXaI1N87camWI_KdwqZq-9w',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/wfUEcOWZmBXsJ4ptmvJW4rZllgY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/P1iTIl0Thy3FWdQhFrhGTwtaigU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/F1h4srqOQmgybWC5L-5jjQMYXV0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ebwUvHqlhucwwZXrOXvFJhH9yMw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/nRlv62YP05F-aG2n6F2EkCQQbEs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/VOZ_erF5m50DsKpGejF5V-WWMFw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/_DUvk991Y6_L8O5M2d878e6h-sM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/WwSn8z8vNu-NPyc6jPIcGwsoSs0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/0exqZekF70p9PZNKBnuCsVcmm78',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/JoJxAEZ-TSeWRaCz8XiIrYjtyTs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/8rlbmdoETsfBtCwYj3U_soUcWK4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Ouhl6VfJfwsTbxXvxpUyBJiqp2c',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/3IAEflNc10q_W-4hj7rZksCxdfo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/hrCKj39nYQ5NXIloGuIPYgU9qKY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/aC8Rq7MpMJwTvKRtx2H-DvCPwuI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/MSFEmBw_uSB0N3MAsVpZ28F8BU8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/evxLbmVcNWMJ0u_B0nTcaBti2t4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/nQNoJ39QCZC9ZwbE_F05YvP4seM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/qTP2Oj2L2v8CmO0TizF4oa6Qav4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/XvK78H2i19cBa5Szw6Ytlw3wUI0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/J6kodNG6S7OOcQ_NKeYJqpFj1rQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/w9J7_Hm6dSP8iossTH-TnAyP2G0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/1vJvhA9gw7cd-7D_i7g1FFWafQs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/dTUKJ5GUCJe739uf--vCLXzzfMI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/CZnHK_n4c_c4ArvmmX55qUhrQOQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/rtNLSrl9WC5_ni19Pm-P51mVJg4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/3pqxJNARLJ1xuKDC6KQLDDUl0xw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/yUgS63GV8Th3_b7Oc4j5D1Fw9fs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ov1xVZMRzXIBnYpTAaV7Xv6UuKc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/pzrIOII_etjIAARYDE1PXJn3wmI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/4lilzi06P-KTiCMxJdb4obG-tdA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/8WplRgaYYxrWKLrGXLJyu7hSUtI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/8J6667DKHvtzoRKfeH-mjtjC9jc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/LgnRN5owEBmYvAfo_52jfMt5Op0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/X1bDXI33SR16018YkLY4pCFm0NI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/N8q3Z9hphgINg7Yj0GLwgSIfSic',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/xq0mfGHowafkfK_rKbwqLOl8ACA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/uZEyRqNC3SyqeHPHUAX5AhcgELY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/q-rolAdMYqttMuSFg0ebIcR7EZw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ok8HtcJtFqmqyzniylhGKmaF1lE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/XcPyOx4iatQNB3JrN5kbmxai91A',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/yLrBzCO2kR7v0tIiCyAAG-t9vTI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/OTDlcPzvpT_cUbRlKbzqLmHa8t4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/lbv_LtNCFT40fymYlkxY9bV-0F0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/HfTdXONDzBQM23iMaFo84qX16JQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/qRXr9eUckiQiQHeeXUqAmuZ2Z54',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/DZ1BGn_lcD_i6rDJRLitDTN0nV4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/73J91Sk903YTvnWRIFUdCUnHYr4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Z1XpWlMZaDEH_CS_FnfyF18mJsU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/m0r12hG1_hqIuD6J0Hr1IRaCI5I',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/EJxvkgyLF6TyKIfVeBCu24VwyLk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/MbUb1tfMbzdWH9Pdr2jJr9iwipc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/pDJ47ZxJaaT91vKpdLMSL7zX54E',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/HjLC-oE6VypVdL7P3kGa6jYGWvE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/_rWwiJ8GAp0qL95stQ1hPkuo8Pk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/KjtvVkXoP54ebupNynXAKc4_U3U',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/9DEfCwN8ZKY7GH29RvVQJLXTgm4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/swGWaE0U0Wt9LCW9jZwi_u1KViA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/vex4GuisAo2VwURgW1bpmO9KgS8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/nhUUXrAONZ2bYoyXyPIrBBMHYrg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/wL9m5nAB_3VHgUtjOGfztZeNmCY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ZSZNyCpaoG2A726AwWgEVf27e4A',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/hOuAk_e9G3GknT7xm_RO8FP9Ujk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/wrti6SbOGg6iLKy9jv-0MOlqmkk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/PiRZtmQYTX4ZghMGzGCX9dDSb48',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/J2jH3KF3suWUyiNR5GpRoErtWUI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/svzfOll3wVgpLCqslvhtwamph9Y',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/SsGdaiFdn2THk50KSxlg69FdEhY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/q9E3qqJEZ1aBtZO0dbPnlZjy4OI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/O1yX3IZ9M_1rJrTJ4iRv7Nr1l0w',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/QSninbNmddIawF4IG6fsd50z55Y',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/uEwHczv24tCY3fAyjRLp8-knwr0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Bx6tjNIaIhBxbBptFYIYzjoRU9M',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/g5H-nkH-0TSNL6nnyB6D7qOP7X8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/O4VCfQOQ-fB14f9tPQD6tPSAHL8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/75ONp09LYkKmesoX1vnoX_SikSI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/KnPF7Nt7xDkIY_epU19UI5rJ0Uo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/gDxOswCTWZxWqJeARG-ORdjThDs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Jor2X_mqWu0SMHqURYWP3b3BLvk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/BtKaddyNWDz99iVZyo6EZm8Ikl0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/OF_g-nSEeZO72XvvShiU6O12wxE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/0oGIXCixGlcirJ9CD8bXcwsjMJE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/IEvrKHBfGxEJcUEYDQTXvHN2DSc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ZqAgzpIeDo1O8Mm0BQClM7gtpJk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/GjUc4V2bogbF_FSBeo9SI_e45Ow',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/whNpRlp6x5kZYChrWMBHZkWVJ2I',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/CjkAVQfl3N5PmeiUHoyBvqChVIw',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/l1SV7bABudVLZJuVYExmg-jiSPc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/FLsRA_j7IPd36JhIJZ3Rw0gDijE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/LVxmpJD9HbDMIFt-bKhmqZo_eSE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/t3fgW5jIbmYVG5IoclOodkvqmgQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/iyyvHSNewL2B1Wdi5hK7V-NDA4g',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ZyNLN9k51Syq67Zy_7_C6wnSYdg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/PXbWGeG7_VV2ybKjIF7XxdFrCII',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zg4X_Kgc2Zyi44IUdtNI3kMJEKQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/1aI7TQh9aoaf5R4pm9XRxpO9etA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/V_VgzWv3nIDTLEFo8Jir3RNaiFs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/b6ix7G9dSTZAccgESS5P_WHPhFs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ihYxv4U-EUzMUNprBPU3NnmsTOA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/2-qcYwXNEnn81qjxwuJbccLoZJg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/7AA1yk4qc98RIlUF2synee9BiIU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/E3-3bmN_eJWzSvsVQqjQHnk31zY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/1xR7Xy1Td3AhttirrouKKBsW34A',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/5KV62tCro5McMrsknBj9_XbAeD8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/vpGQaUqhYMIcR6ZfKZ4CUcKYVig',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/JuZd9FwNuvfkjlgluHj3iM39hGA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/YscQs3WTn7UwrNZ7vxL1EZqJfcY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/f6fJer845sNWCa6nRwDMjgQWrmk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/CbkF9l8S-qgzh-KDVjeHy529UOo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Da3qlOUsN3jZnNFBBP9djZmohkA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Lbf-BuJzVfNp7EBtu_O6Z8pCKys',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/ucrI4cdApSD8rllM8OlsbhEesEs',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/tZFAYP14n5_219Sk-hdVoMHj1HI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/YIqqOyUzWwvQ1qdjj4nfx6j4lto',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Su3p4YGo6OGSwU4O4GKuc8G25w0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/BxRNK8iIVxsSpn2MYHWt_FKy2rY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/JqJB2LyjKPHTw9PAMCuXJ6yoE84',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/9TFdb7NQd-hs1NfArqmBlwQbP48',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/imSuCm2u9oQiR82PncyOLn40gqY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/D5kG2c8KHeSMmlJW3DkMYo4COIk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/N0qy9LQcsIItxsvulxbo8uj8NmI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/w7rGxVU5Li-1dUEC6KJZ6EGJ5Hc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Gs7Wjk2Amq4YYWs9H6kLqhv1o0M',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/6CqwimZzEpjnn47kngoRRUVADq4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/SxGSMQ43x-yTJhBrsRVezxHOU7Y',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/xyrp8zdFdUMbJ7fivbGMXRwc2yI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zVc4vsiQmERRuYGh_hxNSSLFqEU',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/-AucuCO6FV1pl8fEx1V9VaEV8BA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/mlTsJJV_1l-oXeuwrIT_Dov-RC0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/_mhu20HmrOvOIBL8pnqFgvOHAVY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/p3pbwPx75lqy9QPynu4Z-oXk6EI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/UaKJe_kaORyySFNUzlR43opwGOg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/LY-35Hs0K0hBZdPds391djgoWAQ',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/LcqU5Zmf5EQcIPcgQhwjTRGu17A',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/_SwLrhWMFwjqoXQHmJ0xoCsq4I4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/4ngKYXmdHJ5hZFmV6jyUOHm3uF8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/8rYXv741yXtnx765ACCSt0LWQNo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/pM8sTYb9227NlzxIhsyAhPMxsx8',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/H1E7T4ZtozA2uW-P7oeVzGMidQE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/tZNo8dogjFXKVJCc2vI4_5mmaZ0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/detVMSObj6pcCDE9S_udL8YJrbE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/SpKHIKVdNi1HOdUAZYGO3hsHe7M',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/iAUZIrktw2uiR-Qpm_mq7F24EpA',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/1q8seGRCKCpLA7hC6fBYv9IMyc0',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Jj8M_3nfPo-bxTF5puPK460veAE',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Crfsr3LBkWneSBPPAkpMv9B7lx4',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/YbEt5WpFiX31LZ4hBNtHVUL-Ado',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/neoR5dsIxsJIjv_Ez5Hawt7W61c',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/SKn7gHWxc7GlUKY_Zuo0AHZpfxI',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/sRc9eEvkkuLEgpQXOPOLGaxL608',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/tMKFsS75w10jk1KZIBDLbCfPMbg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/Qnqc6r5PABgZLWlrKX6mXwNRXls',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/X5maUtLrYpY7lY-fBM70M2Gd7TM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/_aUG93ToUK_UqwkWMO35gifH9ow',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/2gpHFjzA_eNkKB1z05DuRZQtajg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/glSRtwx7KX4Fi5lC8fcx1pmnqBo',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/VPXca0cOX9rDmffGP4pIlgVX9Cc',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/bfnK8ewuj96l6OuYQQU2pybEf1w',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/lKj4CRO7MZWEGnH_dHVkFtAhJmk',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/HAF6Bee7zz2Qc-5WW4e-Wl0B2Js',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/iAUq9rQi9fpNRY6qW9WpzATSNcM',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/OOPrUEReIyztV4uwF8vHfQ28Wgg',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/9hjsbE_XJ61Zo6Xj7iZVQj51eLY',
'https://find-and-update.company-information.service.gov.uk/disqualified-officers/natural/zTZPJBGizRouXGVCSH22Aan4qYE']


for profile in allprofiles:
    driver.get(profile)
    time.sleep(2)
    
    for i in range(2, 52): # the hyperlink of the names to each profile
        try:
            x = '//*[@id="content-container"]/header/h1'
        # //*[@id="content-container"]/header/h1
        # //*[@id="content-container"]/header/h1
        # //*[@id="content-container"]/header/h1
        # //*[@id="content-container"]/header/h1
        # //*[@id="content-container"]/header/h1 - last on page # 10
            name = driver.find_element(By.XPATH, x).text

        except NoSuchElementException:
            name = 'no name'

        try:
            y = '//*[@id="content-container"]/div[1]/dl[1]/dd'
            # //*[@id="content-container"]/div[1]/dl[1]/dd
            # //*[@id="content-container"]/div[1]/dl[1]/dd
            # //*[@id="content-container"]/div[1]/dl[1]/dd - last on page # 10
            dob = driver.find_element(By.XPATH, y).text 
        except NoSuchElementException:
            dob = 'no DOB'

        
        try:
            z = '//*[@id="content-container"]/div[1]/dl[2]/dd'
            # //*[@id="content-container"]/div[1]/dl[2]/dd
            # //*[@id="content-container"]/div[1]/dl[2]/dd
            # //*[@id="content-container"]/div[1]/dl[2]/dd - last on page # 10
            nationality = driver.find_element(By.XPATH, z).text
        except NoSuchElementException:
            nationality = 'no nationality'

        try:
            a = '//*[@id="content-container"]/div[2]/dl[1]/dd'
            address = driver.find_element(By.XPATH, a). text
        except NoSuchElementException:
            address = 'no address'

        try:
            b = '//*[@id="content-container"]/div[2]/div[1]/dl[1]/dd'
            startDate = driver.find_element(By.XPATH, b).text
        except NoSuchElementException:
            startDate = 'no startDate'
        
        try:
            c = '//*[@id="content-container"]/div[2]/div[1]/dl[2]/dd'
            endDate = driver.find_element(By.XPATH, c).text
        except NoSuchElementException:
            endDate = 'no endDate'

        try:
            d = '//*[@id="content-container"]/div[2]/div[2]/dl/dd'
            caseRef = driver.find_element(By.XPATH, d).text
        except NoSuchElementException:
            caseRef = 'no caseRef'

        
    print(profile + '!' + name + '!' + dob + '!' + nationality + '!' + address + '!'  + startDate + '!' + endDate  + '!' + caseRef) 
    with open(r'C:\Users\Karolina.Gugudis\Desktop\Directors names, DOB.csv', 'a', encoding="utf-8") as f: # a is for appending information to the file
        f.write(profile + '!' + name + '!' + dob + '!' + nationality + '!' + address + '!'  + startDate + '!' + endDate  + '!' + caseRef + '\n' )
 
print('the job is done')